### ISSUE TITLE
Sequential download and streaming for ADC 

### ISSUE THREAD

**Issue by ravaan** [gswly/dctoolkit#2]
Is there a sequential download option available for ADC protocol?

I also wanted to ask whether there is a way to directly stream a TTH/Magnet of a file from an ADC Hub, wasn't able to find any implementation online as of yet.

I was working on making a streaming service on top of the DC network we have on our campus.

**Comment by gswly** [comment]
Hi, thanks for your interest in this project.

Regarding sequential download, i suggest you to create a queue and start each download when the previous one is complete. For instance:
```
type myDownload struct {
    peerName string
    tth string
}

func main() {
    seqDownloads := []myDownload{
        { "peer1", "TTH1" },
        { "peer2", "TTH2" },
    }

    client, err := dctk.NewClient(dctk.ClientConf{
        HubUrl:     "nmdc://hubip:411",
        Nick:       "mynick",
        TcpPort:    3009,
        UdpPort:    3009,
        TcpTlsPort: 3010,
    })
    if err != nil {
        panic(err)
    }

    popDownload := func() {
        if len(seqDownloads) == 0 {
            fmt.Println("all downloads processed")
            client.Close()
            return
        }

        dl,seqDownloads := seqDownloads[0], seqDownloads[1:]
        peer := client.Peers()[dl.peerName]
        if peer == nil {
            fmt.Println("peer not connected")
            popDownload()
            return
        }

        client.DownloadFile(dctk.DownloadConf{
            Peer: p,
            TTH:  dctk.TigerHashMust(dl.tth),
        })
    }

    client.OnHubConnected = func() {
        popDownload()
    }

    client.OnDownloadSuccessful = func(d *dctk.Download) {
        popDownload()
    }

    client.OnDownloadError = func(d *dctk.Download) {
        popDownload()
    }

    client.Run()
}
```

Unfortunately DC requires the exact peer and TTH to start a download. If you don't know them or you want to download from ANY available peer and not from a specific one, start a search with Search().

Regarding streaming, this project was indeed started for streaming files from a DC hub :)
Just set a chunk size and download chunk by chunk.
I've added an example in the example folder.

In a next release i'll add the possibility to users of providing their own io.Writer, such that chunk downloading is not necessary anymore.
